// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"learnZero/greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 注册路由
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: GreetHandler(serverCtx),
			},
		},
	)
}
